# Generated by Django 5.1.1 on 2024-10-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='face_encoding',
            field=models.TextField(default=[]),
            preserve_default=False,
        ),
    ]
