# Generated by Django 5.1.1 on 2024-10-15 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofile_face_encoding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='face_encoding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
