# Generated by Django 5.1.1 on 2024-10-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_userprofile_teaching_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='teaching_subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
