# Generated by Django 5.1.1 on 2024-10-26 02:15

import authentication.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_userprofile_teaching_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='face_image',
            field=models.ImageField(upload_to='face_images/', validators=[authentication.validators.validate_image_format]),
        ),
    ]
