# Generated by Django 5.1.1 on 2024-10-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_userprofile_face_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='teaching_subject',
            field=models.CharField(blank=True, default='unknown', max_length=100, null=True),
        ),
    ]
