# Generated by Django 5.1.2 on 2024-10-27 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='courses/'),
        ),
    ]
