# Generated by Django 5.1.1 on 2024-10-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stress_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stressassessment',
            old_name='question_1',
            new_name='Q1',
        ),
        migrations.RenameField(
            model_name='stressassessment',
            old_name='question_2',
            new_name='Q2',
        ),
        migrations.RenameField(
            model_name='stressassessment',
            old_name='question_3',
            new_name='Q3',
        ),
        migrations.RemoveField(
            model_name='stressassessment',
            name='created_at',
        ),
        migrations.AddField(
            model_name='stressassessment',
            name='Q4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stressassessment',
            name='Q5',
            field=models.IntegerField(default=0),
        ),
    ]
